package com.lovecoding.pojo;

import java.io.Serializable;

public class BmsBook implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_book.id
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_book.book_name
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_book.book_author
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private String bookAuthor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bms_book.book_price
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private String bookPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_book.id
     *
     * @return the value of bms_book.id
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_book.id
     *
     * @param id the value for bms_book.id
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_book.book_name
     *
     * @return the value of bms_book.book_name
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_book.book_name
     *
     * @param bookName the value for bms_book.book_name
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_book.book_author
     *
     * @return the value of bms_book.book_author
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_book.book_author
     *
     * @param bookAuthor the value for bms_book.book_author
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bms_book.book_price
     *
     * @return the value of bms_book.book_price
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public String getBookPrice() {
        return bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bms_book.book_price
     *
     * @param bookPrice the value for bms_book.book_price
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setBookPrice(String bookPrice) {
        this.bookPrice = bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", bookName=").append(bookName);
        sb.append(", bookAuthor=").append(bookAuthor);
        sb.append(", bookPrice=").append(bookPrice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}