package com.lovecoding.pojo;

import java.io.Serializable;

public class OmsOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.oid
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private Long oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.ono
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private String ono;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.total_amount
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private String totalAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oms_order.user_id
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oms_order
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.oid
     *
     * @return the value of oms_order.oid
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public Long getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.oid
     *
     * @param oid the value for oms_order.oid
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setOid(Long oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.ono
     *
     * @return the value of oms_order.ono
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public String getOno() {
        return ono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.ono
     *
     * @param ono the value for oms_order.ono
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setOno(String ono) {
        this.ono = ono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.total_amount
     *
     * @return the value of oms_order.total_amount
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public String getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.total_amount
     *
     * @param totalAmount the value for oms_order.total_amount
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oms_order.user_id
     *
     * @return the value of oms_order.user_id
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oms_order.user_id
     *
     * @param userId the value for oms_order.user_id
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oms_order
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", oid=").append(oid);
        sb.append(", ono=").append(ono);
        sb.append(", totalAmount=").append(totalAmount);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}