package com.lovecoding.pojo;

import java.io.Serializable;

public class UmsUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_user.id
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_user.name
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_user.username
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_user.password
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_user.amount
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ums_user.sex
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ums_user
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_user.id
     *
     * @return the value of ums_user.id
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_user.id
     *
     * @param id the value for ums_user.id
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_user.name
     *
     * @return the value of ums_user.name
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_user.name
     *
     * @param name the value for ums_user.name
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_user.username
     *
     * @return the value of ums_user.username
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_user.username
     *
     * @param username the value for ums_user.username
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_user.password
     *
     * @return the value of ums_user.password
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_user.password
     *
     * @param password the value for ums_user.password
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_user.amount
     *
     * @return the value of ums_user.amount
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_user.amount
     *
     * @param amount the value for ums_user.amount
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ums_user.sex
     *
     * @return the value of ums_user.sex
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ums_user.sex
     *
     * @param sex the value for ums_user.sex
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", amount=").append(amount);
        sb.append(", sex=").append(sex);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}