package com.lovecoding.mapper;

import com.lovecoding.pojo.BmsBook;
import com.lovecoding.pojo.BmsBookExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BmsBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    long countByExample(BmsBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    int deleteByExample(BmsBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    int insert(BmsBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    int insertSelective(BmsBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    List<BmsBook> selectByExample(BmsBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    BmsBook selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    int updateByExampleSelective(@Param("record") BmsBook record, @Param("example") BmsBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    int updateByExample(@Param("record") BmsBook record, @Param("example") BmsBookExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    int updateByPrimaryKeySelective(BmsBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bms_book
     *
     * @mbg.generated Mon Aug 02 15:07:23 CST 2021
     */
    int updateByPrimaryKey(BmsBook record);
}